server:
    port: ${myport:8888}
ibm:
    mq:
        queueManager: QM_JAVA_TEMPLATE
        channel: DEV.ADMIN.SVRCONN
        connName: localhost(1414)
        user: admin
        password: passw0rd
        queue: DEV.QUEUE.1
        queue2: DEV.QUEUE.2
